stages:
- name: backend-test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: 'cd backend && cp ./config/config.example.json ./config/config.json
        && npm i && npm test '
timeout: 60
notification: {}
