/**
 * Footprint API
 * API for calculating your Carbon footprint
 *
 * OpenAPI spec version: 0.1.0
 * Contact: apiteam@codefor.nl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type LocationType = 'Address' | 'Airport' | 'Harbour' | 'Train Station' | 'Bus Station' | 'Marina' | 'Place' | 'Venue';

export const LocationType = {
    Address: 'Address' as LocationType,
    Airport: 'Airport' as LocationType,
    Harbour: 'Harbour' as LocationType,
    TrainStation: 'Train Station' as LocationType,
    BusStation: 'Bus Station' as LocationType,
    Marina: 'Marina' as LocationType,
    Place: 'Place' as LocationType,
    Venue: 'Venue' as LocationType
};
