/**
 * Footprint API
 * API for calculating your Carbon footprint
 *
 * OpenAPI spec version: 0.1.0
 * Contact: apiteam@codefor.nl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type TransportType = 'Plane' | 'Car' | 'Bike' | 'Foot' | 'Bus' | 'Train' | 'Boat' | 'Taxi';

export const TransportType = {
    Plane: 'Plane' as TransportType,
    Car: 'Car' as TransportType,
    Bike: 'Bike' as TransportType,
    Foot: 'Foot' as TransportType,
    Bus: 'Bus' as TransportType,
    Train: 'Train' as TransportType,
    Boat: 'Boat' as TransportType,
    Taxi: 'Taxi' as TransportType
};
