/**
 * Footprint API
 * API for calculating your Carbon footprint
 *
 * OpenAPI spec version: 0.1.0
 * Contact: apiteam@codefor.nl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';
import { TransportType } from './transportType';


export interface Travel { 
    id?: number;
    sequence?: number;
    departedAt?: string;
    arrivedAt?: string;
    transport?: TransportType;
    departure?: Location;
    arrival?: Location;
}
